package base

// Comments added to files that are altered by Wharf
const (
	TAG_NOTICE     = "Tags altered by Wharf (added %v)"
	FILE_NOTICE    = "This file was generated by Wharf (original %v)"
	USE_NOTICE     = "Imported by Wharf (version %v)"
	REPLACE_NOTICE = "Added by Wharf"
)
